import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const projects=[
 {id:'01',name:'TROVE',type:'WEB APP',desc:'A modern product experience focused on discovering, organizing and exploring digital resources.',stack:['JavaScript','UI','APIs'],url:'https://github.com/yourasmit15-web/TROVE',status:'BUILD'},
 {id:'02',name:'DHUN',type:'WEB APP',desc:'A music-focused web experience designed around discovery and playing without a subscription layer.',stack:['Web','UI','Media'],url:'https://github.com/yourasmit15-web/TROVE',status:'EXPERIMENT'},
 {id:'03',name:'REALSENSE',type:'BROWSER EXTENSION',desc:'Turns real user interactions into actionable runtime insights to help developers understand what went wrong and why.',stack:['JavaScript','Browser APIs','UX'],url:'https://github.com/yourasmit15-web',status:'BUILD'},
 {id:'04',name:'JARVIS AI ASSISTANT',type:'AI / ASSISTANT',desc:'An AI assistant concept exploring natural-language interaction, useful actions and developer-oriented automation.',stack:['AI','Python','APIs'],url:'https://github.com/yourasmit15-web',status:'EXPERIMENT'},
 {id:'05',name:'YOUTUBE TRIMMER',type:'WEB TOOL',desc:'A focused utility for trimming video content into precise clips worth keeping.',stack:['JavaScript','Video','Web'],url:'https://github.com/yourasmit15-web',status:'BUILD'},
 {id:'06',name:'MEDINFOAI',type:'AI / ML',desc:'An AI product concept for turning medicine information into a more accessible digital experience.',stack:['AI','ML','Web'],url:'https://github.com/yourasmit15-web',status:'EXPERIMENT'}
];
const skills=[['01','HTML','DEVELOPMENT'],['02','CSS','DEVELOPMENT'],['03','JAVASCRIPT','DEVELOPMENT'],['04','REACT','DEVELOPMENT'],['05','NODE.JS','DEVELOPMENT'],['06','PYTHON','AI & DATA'],['07','MACHINE LEARNING','AI & DATA'],['08','SQL','AI & DATA'],['09','APIs','DEVELOPMENT'],['10','GIT','TOOLS'],['11','GITHUB','TOOLS'],['12','LINUX','INFRASTRUCTURE'],['13','UI / UX','CREATIVE'],['14','GENERATIVE AI','AI & DATA'],['15','FIREBASE','INFRASTRUCTURE']];

const wall=$('#skillWall');skills.forEach(([n,name,cat])=>{const e=document.createElement('div');e.className='skill';e.dataset.cat=cat;e.innerHTML=`<span class="num">${n}</span><b>${name}</b><small>${cat}</small>`;wall.appendChild(e)});

const list=$('#projectList'),feature=$('#projectFeature');
function renderProjects(){
 const p=projects[0]; feature.innerHTML=`<div class="feature-copy"><small>FEATURED BUILD · ${p.type}</small><h3>${p.name}</h3><p>${p.desc}</p><a class="text-link" href="${p.url}" target="_blank" rel="noreferrer">OPEN REPOSITORY ↗</a></div>`;
 list.innerHTML='';projects.slice(1).forEach(p=>{const e=document.createElement('article');e.className='project';e.tabIndex=0;e.innerHTML=`<span class="project-index">${p.id} / ${p.status}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${p.stack.map(x=>`<span>${x}</span>`).join('')}</div><span class="open">VIEW CASE ↗</span>`;e.addEventListener('click',()=>openCase(p));e.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' ')openCase(p)});list.appendChild(e)});
}
renderProjects();

function openCase(p){const modal=$('#projectModal'),content=$('#modalContent');content.innerHTML=`<div class="case"><div class="kicker">PROJECT ${p.id} / ${p.type}</div><h2>${p.name}</h2><p>${p.desc}</p><div class="case-grid"><div class="case-block"><small>PROBLEM</small><h3>What needed to be solved?</h3><p>A focused digital experience needs a clear user goal, simple interaction and reliable implementation. This build explores that problem through a working product concept.</p></div><div class="case-block"><small>IDEA</small><h3>Make the experience obvious.</h3><p>The interface is shaped around the primary action first, with technology supporting the experience rather than becoming decoration.</p></div><div class="case-block"><small>BUILD</small><h3>${p.stack.join(' · ')}</h3><p>The project is approached as an end-to-end build: interface, behavior, data/API integration where required, debugging and iteration.</p></div><div class="case-block"><small>RESULT</small><h3>Something you can explore.</h3><p>Status: ${p.status}. Open the repository to inspect the implementation and current state.</p></div></div><div class="case-links"><a href="${p.url}" target="_blank" rel="noreferrer">GITHUB ↗</a></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCase(){$('#projectModal').classList.remove('open');$('#projectModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#modalClose').onclick=closeCase;$('#projectModal').addEventListener('click',e=>{if(e.target.id==='projectModal')closeCase()});

const nav=$('#nav'),progress=$('#progress'),sections=$$('main section[id]');
function scrollUI(){const y=scrollY;nav.classList.toggle('scrolled',y>30);progress.style.width=`${Math.min(100,(y/(document.documentElement.scrollHeight-innerHeight))*100)}%`;let active='home';sections.forEach(s=>{if(y+innerHeight*.35>=s.offsetTop)active=s.id});$$('.nav nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+active))}addEventListener('scroll',scrollUI,{passive:true});scrollUI();

$('#menuBtn').onclick=()=>$('#mobileMenu').classList.add('open');$('#menuClose').onclick=()=>$('#mobileMenu').classList.remove('open');$$('#mobileMenu a').forEach(a=>a.onclick=()=>$('#mobileMenu').classList.remove('open'));

const cursor=$('#cursor');addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});$$('a,button,.project,.skill').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('hover-cursor'));el.addEventListener('mouseleave',()=>cursor.classList.remove('hover-cursor'))});

$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(max-width:700px)').matches)return;const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});

const toast=(t)=>{const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2600)};
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=encodeURIComponent('Portfolio inquiry from '+f.get('name'));const body=encodeURIComponent(f.get('message')+'\n\nReply to: '+f.get('email'));location.href=`mailto:yourasmit108@gmail.com?subject=${subject}&body=${body}`;toast('Opening your email client…')});

let audioOn=false,audioCtx=null;$('#sound').onclick=()=>{audioOn=!audioOn;$('#sound').textContent=audioOn?'SOUND ON':'SOUND OFF';if(audioOn){audioCtx ||= new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=440;g.gain.value=.025;o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.08)}};

async function loadRepos(){const el=$('#repos');try{const r=await fetch('https://api.github.com/users/yourasmit15-web/repos?per_page=6&sort=updated');if(!r.ok)throw Error('GitHub API unavailable');const data=await r.json();if(!Array.isArray(data)||!data.length)throw Error('No repositories');el.innerHTML=data.map(x=>`<article class="repo"><small>${(x.language||'CODE').toUpperCase()} · ${x.visibility?.toUpperCase()||'PUBLIC'}</small><h3>${x.name}</h3><p>${x.description||'Public repository by Asmit Mishra.'}</p><div class="repo-foot"><span>★ ${x.stargazers_count||0}</span><span>FORKS ${x.forks_count||0}</span><a class="text-link" href="${x.html_url}" target="_blank" rel="noreferrer">OPEN ↗</a></div></article>`).join('')}catch(err){el.innerHTML=`<article class="repo" style="grid-column:1/-1"><small>PUBLIC DATA</small><h3>GitHub activity is temporarily unavailable.</h3><p>Open the public profile directly to see the latest repositories and activity.</p><div class="repo-foot"><a class="text-link" href="https://github.com/yourasmit15-web" target="_blank" rel="noreferrer">OPEN GITHUB ↗</a></div></article>`}}loadRepos();

// Lightweight Three.js hero: a stylized developer workspace with real-time mouse parallax.
let renderer,scene3,camera3,group,raf;const canvas=$('#world');
function makeMat(c,rough=.55,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}const mats={dark:makeMat(0x111820,.35,.35),cyan:makeMat(0x67e8f9,.25,.6),desk:makeMat(0x342a25,.8),light:makeMat(0xd8fbff,.2,.2),glass:new THREE.MeshPhysicalMaterial({color:0x67e8f9,transparent:true,opacity:.12,roughness:.1,metalness:.2})};
function cube(x,y,z,w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;group.add(o);return o}
function buildWorld(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;scene3=new THREE.Scene();scene3.fog=new THREE.FogExp2(0x071016,.045);camera3=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100);camera3.position.set(0,3.2,12);group=new THREE.Group();scene3.add(group);
 const hemi=new THREE.HemisphereLight(0xbdeaff,0x071016,1.8);scene3.add(hemi);const key=new THREE.PointLight(0x67e8f9,35,25);key.position.set(1,5,4);key.castShadow=true;scene3.add(key);const rim=new THREE.PointLight(0xa78bfa,20,20);rim.position.set(-6,3,0);scene3.add(rim);
 cube(0,-.35,0,20,.5,14,mats.dark);cube(0,.8,-1,7,.2,3,mats.desk);cube(0,1.5,-1.1,4.2,.15,.15,mats.dark);
 const mon=cube(0,2.5,-1.3,3.8,2.1,.15,mats.dark);cube(0,2.5,-1.38,3.45,1.72,.03,mats.glass);cube(0,1.9,-1.32,.3,.5,.3,mats.dark);cube(0,1.66,-1.32,1.3,.12,.5,mats.dark);
 for(let i=0;i<10;i++)cube(-1.7+i*.38,1.72,-.8,.23,.03,.5,i%2?mats.cyan:mats.light);
 for(let i=0;i<4;i++){const h=.8+i*.45;cube(4+i*.4,h,-2,.2,h,.2,mats.cyan)}
 for(let i=0;i<12;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.025+Math.random()*.045,8,8),mats.cyan);p.position.set(-7+Math.random()*14,1+Math.random()*6,-5+Math.random()*5);group.add(p)}
 for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.4+i*.45,.012,8,80),mats.cyan);ring.position.set(4,3+i*.35,-2);ring.rotation.x=Math.PI/2.3;group.add(ring)}
 addEventListener('pointermove',e=>{if(innerWidth<800)return;const nx=e.clientX/innerWidth-.5,ny=e.clientY/innerHeight-.5;group.rotation.y=nx*.08;group.rotation.x=-ny*.045;camera3.position.x=nx*.8;camera3.position.y=3.2-ny*.5;camera3.lookAt(0,1.6,-1)});const animate=()=>{raf=requestAnimationFrame(animate);group.children.forEach((o,i)=>{if(o.geometry?.type==='TorusGeometry')o.rotation.z+=.0015*(i%2?1:-1)});renderer.render(scene3,camera3)};animate();}catch(e){canvas.style.display='none'}}buildWorld();
addEventListener('resize',()=>{if(!renderer)return;camera3.aspect=innerWidth/innerHeight;camera3.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.12});$$('.section').forEach(s=>observer.observe(s));
