import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
const root=document.querySelector('.house-app'),canvas=document.createElement('canvas');canvas.className='game-canvas';root.prepend(canvas);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b1511);scene.fog=new THREE.Fog(0x0b1511,24,65);const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,100);camera.position.set(0,1.7,17);const clock=new THREE.Clock();const keys={},walls=[],doors=[],triggers=[];let started=false,locked=false,yaw=0,pitch=0,openRoom=null,tourTimer=0;
const mat=(c,r=.72,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});const M={wall:mat(0x6c716f),floor:mat(0x242b28),wood:mat(0x604733),dark:mat(0x141a18),glass:mat(0x578da0,.12,.35),cream:mat(0xd8d0bd),blue:mat(0x304f5f),green:mat(0x35523e),gold:mat(0xc8a15e,.28,.5),brick:mat(0x713e35)};
function box(n,x,y,z,w,h,d,m,collide=false){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.name=n;o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);if(collide)walls.push({x,z,w,d});return o}
function txt(s,x,y,z,size=.2){const c=document.createElement('canvas');c.width=900;c.height=220;const g=c.getContext('2d');g.fillStyle='#f1eee4';g.font='800 72px Manrope,Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(s,450,110);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const q=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));q.position.set(x,y,z);q.scale.set(size*4.2,size,1);scene.add(q)}
function wall(x,z,w,d){return box('wall',x,1.55,z,w,3.1,d,M.wall,true)}
function light(x,z,power=2.3){const l=new THREE.PointLight(0xffc778,power,8);l.position.set(x,2.85,z);l.castShadow=true;scene.add(l);box('lamp',x,3.05,z,.18,.12,.18,M.gold)}
function door(x,z,label){const d=box(label+' door',x,1.5,z,2,3,.18,M.wood);doors.push({m:d,t:0});txt(label,x,2.75,z,.17);return d}
function room(label,cx,cz,w,d,side,type){box(label+' floor',cx,.04,cz,w,.1,d,M.floor);wall(cx,cz+d/2,w,.18);wall(side==='L'?cx-w/2:cx+w/2,cz,.18,d);const ix=side==='L'?cx+w/2:cx-w/2,gap=2.25;wall(ix,cz-d/2+(d-gap)/4,.18,(d-gap)/2);wall(ix,cz+d/2-(d-gap)/4,.18,(d-gap)/2);door(ix,cz,label);light(cx,cz);txt(label,cx,2.65,cz,.19);triggers.push({name:label,x:ix+(side==='L'?.85:-.85),z:cz});
 if(type==='desk'){box('desk',cx,.72,cz,2.8,.2,1.05,M.wood);box('monitor',cx,1.55,cz-.36,1.65,.85,.1,M.dark);box('chair',cx,.65,cz+1.05,.85,.9,.85,M.blue)}
 if(type==='projects'){for(let i=0;i<5;i++)box('project shelf',cx-2.1+i*1.05,1.2,cz+1.65,.72,2.2,.42,i%2?M.blue:M.green);box('workbench',cx,.7,cz-1.05,3.5,.2,1.1,M.wood)}
 if(type==='education'){for(let i=0;i<3;i++)box('bookcase',cx-1.5+i*1.5,1.4,cz+1.45,1,2.45,.5,M.wood);box('study desk',cx,.7,cz-1,2.8,.2,1,M.wood)}
 if(type==='experience'){box('dev bench',cx,.7,cz,4,.2,1.1,M.wood);for(let i=-1;i<=1;i++)box('screen',cx+i*1.35,1.65,cz-.42,1.05,.7,.1,M.dark)}
 if(type==='contact'){box('meeting table',cx,.62,cz,3.5,.18,1.55,M.wood);for(const dx of [-1.8,1.8])box('chair',cx+dx,.65,cz,.8,.9,.8,M.blue)} }
const content={ABOUT:'I am AsmiT Mishra — a Full-Stack Developer and AI enthusiast focused on turning ideas into useful digital products. I learn by building, shipping and iterating.',SKILLS:'JavaScript · TypeScript · Python · React · Next.js · Node.js · MongoDB · PostgreSQL · Firebase · Git · GitHub · Generative AI. My focus: product thinking, clean interfaces and practical engineering.',PROJECTS:'JARVIS AI ASSISTANT — AI automation. TROVE — music discovery. REALSENSE — intelligent web experience. YOUTUBE TRIMMER — focused utility. MEDINFOAI — AI-assisted information product.',EDUCATION:'BCA (2024–2027) · Meena Shah Institute of Technology and Management. 12th PCM (2022–2024). 10th Science — 84.5%. The goal is to turn formal learning into shipped software.',EXPERIENCE:'Full-Stack Developer Intern · Hivens (Just Inc.) · 2026. Worked across web interfaces, features, debugging, UX and deployment. I care about shipping reliable experiences, not just writing code.',CONTACT:'Let’s build something worth opening. Email: yourasmit108@gmail.com · GitHub: yourasmit15-web · LinkedIn: asmitxmishra · Instagram: @asmitx.dev'};
const links={PROJECTS:[['GitHub','https://github.com/yourasmit15-web']],CONTACT:[['GitHub','https://github.com/yourasmit15-web'],['LinkedIn','https://www.linkedin.com/in/asmitxmishra'],['Instagram','https://www.instagram.com/asmitx.dev/'],['Email','mailto:yourasmit108@gmail.com']]};
box('terrain',0,-.35,0,52,.5,52,mat(0x1c2921),false);box('driveway',0,-.08,17,9,.12,11,mat(0x303534));box('corridor floor',0,.03,-.2,4.3,.1,23,M.floor);
room('ABOUT',-5.5,6,6.6,6,'L','desk');room('SKILLS',5.5,6,6.6,6,'R','desk');room('PROJECTS',-5.5,-1,6.6,7,'L','projects');room('EDUCATION',5.5,-1,6.6,7,'R','education');room('EXPERIENCE',-5.5,-8.4,6.6,6,'L','experience');room('CONTACT',5.5,-8.4,6.6,6,'R','contact');
box('lobby',0,.04,10.2,4.3,.1,4,M.floor);wall(-3.2,11.1,2.1,.18);wall(3.2,11.1,2.1,.18);door(0,11,'ENTRANCE');box('porch',0,.05,13,9,.18,4,M.wood);for(let z=15;z>=12;z--)box('step',0,(15-z)*.14,z,9,.2,.6,M.cream);for(const x of [-2.2,2.2])box('window',x,2.1,10.95,2.1,1.35,.08,M.glass);
box('roof',0,3.45,0,20,.35,24,M.dark);box('roof ridge',0,3.95,0,20,.3,1,M.brick);box('chimney',7,4.2,-4,1.2,2.1,1.2,M.wall);
new THREE.TextureLoader().load('assets/asmit-profile.jpg',tex=>{tex.colorSpace=THREE.SRGBColorSpace;box('profile frame',0,2.05,9.0,2.2,2.6,.12,M.gold);const p=new THREE.Mesh(new THREE.PlaneGeometry(1.8,2.2),new THREE.MeshStandardMaterial({map:tex,roughness:.65}));p.position.set(0,2.05,8.92);scene.add(p)},undefined,()=>{});
for(let i=0;i<20;i++){const x=-20+Math.random()*40,z=-18+Math.random()*36;if(Math.abs(x)<12&&Math.abs(z)<15)continue;box('trunk',x,1,z,.32,2,.32,M.wood);const c=new THREE.Mesh(new THREE.SphereGeometry(1.2+Math.random()*.65,12,8),mat(0x294735));c.position.set(x,2.25,z);c.castShadow=true;scene.add(c)}
for(const x of [-7,-3,3,7])light(x,12.2,1.35);scene.add(new THREE.HemisphereLight(0xb9d1df,0x101810,1.45));const sun=new THREE.DirectionalLight(0xffe2b9,3.2);sun.position.set(-12,18,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;scene.add(sun);
function show(n){openRoom=n;const p=document.querySelector('.panel');p.classList.add('show');p.querySelector('h2').textContent=n;p.querySelector('p').textContent=content[n];const holder=p.querySelector('.panel-links');holder.innerHTML='';(links[n]||[]).forEach(([label,url])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noreferrer';a.textContent=label+' ↗';holder.appendChild(a)});document.querySelector('.room-name').textContent=n+' ROOM';document.querySelector('.toast').classList.remove('show')}
function closePanel(){openRoom=null;document.querySelector('.panel').classList.remove('show');document.querySelector('.room-name').textContent='HOUSE';if(started)canvas.requestPointerLock?.()}
function start(){started=true;document.querySelector('.intro').classList.add('hidden');document.querySelector('.hud').classList.add('active');camera.position.set(0,1.7,17);yaw=0;pitch=0;document.querySelector('.toast').classList.add('show');setTimeout(()=>document.querySelector('.toast').classList.remove('show'),4000)}
document.querySelector('.enter').onclick=()=>{start();canvas.requestPointerLock?.()};document.querySelector('.tour').onclick=()=>{start();tourTimer=.01;canvas.requestPointerLock?.()};document.querySelector('.close').onclick=closePanel;canvas.onclick=()=>{if(started&&!openRoom)canvas.requestPointerLock?.()};document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===canvas);document.addEventListener('mousemove',e=>{if(!locked)return;yaw-=e.movementX*.0022;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-1.2,1.2)});
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Escape'&&openRoom)closePanel()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const touch={up:0,down:0,left:0,right:0};document.querySelectorAll('.mobile-controls button').forEach(b=>{const v=b.dataset.move;b.addEventListener('touchstart',e=>{e.preventDefault();touch[v]=1},{passive:false});b.addEventListener('touchend',e=>{e.preventDefault();touch[v]=0},{passive:false})});
function blocked(x,z){for(const w of walls)if(x>w.x-w.w/2-.3&&x<w.x+w.w/2+.3&&z>w.z-w.d/2-.3&&z<w.z+w.d/2+.3)return true;return false}
const tour=[{x:0,z:14},{x:0,z:10},{x:-4.4,z:6},{x:4.4,z:6},{x:-4.4,z:-1},{x:4.4,z:-1},{x:-4.4,z:-8.4},{x:4.4,z:-8.4}];let ti=0;
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(started&&!openRoom){if(tourTimer){tourTimer+=dt;if(tourTimer>2.2){ti=(ti+1)%tour.length;tourTimer=.01}const t=tour[ti];camera.position.x=THREE.MathUtils.lerp(camera.position.x,t.x,dt*.65);camera.position.z=THREE.MathUtils.lerp(camera.position.z,t.z,dt*.65);yaw=Math.atan2(t.x-camera.position.x,-(t.z-camera.position.z));}else{const f=((keys.w||keys.arrowup)?1:0)-((keys.s||keys.arrowdown)?1:0)||touch.up-touch.down;const r=((keys.d||keys.arrowright)?1:0)-((keys.a||keys.arrowleft)?1:0)||touch.right-touch.left;const dir=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),side=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),sp=4.4*dt;const nx=camera.position.x+(-dir.x*f+side.x*r)*sp,nz=camera.position.z+(-dir.z*f+side.z*r)*sp;if(!blocked(nx,camera.position.z))camera.position.x=THREE.MathUtils.clamp(nx,-10.1,10.1);if(!blocked(camera.position.x,nz))camera.position.z=THREE.MathUtils.clamp(nz,-12,17)}camera.position.y=1.7;camera.rotation.set(pitch,yaw,0,'YXZ');for(const t of triggers)if(Math.hypot(camera.position.x-t.x,camera.position.z-t.z)<1.35)show(t.name)}for(const d of doors){const near=Math.hypot(camera.position.x-d.m.position.x,camera.position.z-d.m.position.z)<2.6;d.t=near?-1.2:0;d.m.rotation.y=THREE.MathUtils.lerp(d.m.rotation.y,d.t,dt*5)}renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});