document.addEventListener('DOMContentLoaded',()=>{
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,fine=matchMedia('(pointer:fine)').matches;
 const reveals=document.querySelectorAll('.reveal');
 if('IntersectionObserver' in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});reveals.forEach(e=>io.observe(e))}else reveals.forEach(e=>e.classList.add('visible'));
 const menu=document.querySelector('.menu-btn'),panel=document.querySelector('.mobile-menu'),close=document.querySelector('.close-menu');
 const setMenu=open=>{panel?.classList.toggle('open',open);panel?.setAttribute('aria-hidden',String(!open));menu?.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''};
 menu?.addEventListener('click',()=>setMenu(true));close?.addEventListener('click',()=>setMenu(false));panel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
 const links=[...document.querySelectorAll('.desktop-nav a')],dots=[...document.querySelectorAll('.room-dots a')],sections=[...document.querySelectorAll('main section[id]')],label=document.querySelector('.room-nav-label');
 const active=()=>{let index=0;sections.forEach((s,i)=>{if(scrollY+innerHeight*.4>=s.offsetTop)index=i});const id=sections[index]?.id||'home';links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));dots.forEach((a,i)=>a.classList.toggle('active',i===index));if(label)label.textContent=`${String(index+1).padStart(2,'0')} / ${String(sections.length).padStart(2,'0')}`};
 addEventListener('scroll',active,{passive:true});addEventListener('resize',active);active();
 document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const h=a.getAttribute('href'),t=h&&document.querySelector(h);if(t){e.preventDefault();t.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}}));
 const progress=document.querySelector('.scroll-progress'),update=()=>{if(progress){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?scrollY/max*100:0}%`}};addEventListener('scroll',update,{passive:true});update();
 const glow=document.querySelector('.cursor-glow');if(glow&&fine&&!reduce){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});const loop=()=>{x+=(tx-x)*.12;y+=(ty-y)*.12;glow.style.left=x+'px';glow.style.top=y+'px';requestAnimationFrame(loop)};loop()}
 const scene=document.querySelector('.house-scene');if(scene&&fine&&!reduce){let raf=0;scene.addEventListener('pointermove',e=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const r=scene.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;scene.style.transform=`rotateX(${(-y*1.8).toFixed(2)}deg) rotateY(${(x*2.2).toFixed(2)}deg)`})},{passive:true});scene.addEventListener('pointerleave',()=>scene.style.removeProperty('transform'))}
 const filters=document.querySelectorAll('.filter'),cards=document.querySelectorAll('.project-card');filters.forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.filter;filters.forEach(x=>x.classList.toggle('active',x===b));cards.forEach(c=>{const show=v==='all'||c.dataset.category===v;c.classList.toggle('is-hidden',!show)})}));
 if(fine&&!reduce)document.querySelectorAll('.project-card,.skill-card,.facts div,.experience-card,.contact-links a').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=e.clientX/r.width-r.left/r.width-.5,y=e.clientY/r.height-r.top/r.height-.5;card.style.transform=`translateY(-7px) rotateX(${(-y*3).toFixed(2)}deg) rotateY(${(x*3).toFixed(2)}deg) translateZ(12px)`},{passive:true});card.addEventListener('pointerleave',()=>card.style.removeProperty('transform'))});
 document.querySelectorAll('a[target="_blank"]').forEach(a=>a.setAttribute('rel','noopener noreferrer'));
});